services:
- type: web
  name: cratejuice-backend
  env: python
  plan: free
  buildCommand: pip install -r apps/backend/requirements.txt
  startCommand: uvicorn apps.backend.main:app --host 0.0.0.0 --port $PORT
